
# Configuration

title: Irvin Herrera
author:
  name: Irvin Herrera
  title: Software Engineer
language: 'en-us'
description: >
  Personal website and Blog
url: 'https://herrirvin.com'
twitter_username: irvinhg
google_analytics: TODO
baseurl: ""
show_dir_listing: false
year: 2023
permalink: "/blog/:year-:title"

# Tags : Using 'jekyll-catgenerator' plugin in _plugins folder
tag_path: "/blog/tag/"

# Pagination

paginate: 5
paginate_path: "/blog/page:num/"

# Build settings

markdown: kramdown
highlighter: rouge

# Contact links

contact:
  #googleplus : ''
  github: 'https://github.com/vinniehg'
  twitter: 'https://twitter.com/irvin_herrera'
  linkedin: 'https://fr.linkedin.com/in/irvin-herrera-6350a726'
  #facebook: ''
  blog: '/blog'

# CDN

cdn_baseurl: 'https://s3.eu-west-3.amazonaws.com/herrirvin-eu1'

# Gems & other

plugins: [jekyll-paginate]

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  
